<div class="row bg-secondary text-white">
        <div class="col-12 text-center my-5 ">
        <h1 class="display-3">Empresas</h1>
        </div>
        </div> 
        <div class="col-12 text-center my-5">
            <h3 class="display-4">Conheça as Empresas parceiras</h3>
            <br>
          </div>    
          <div class="col-12 text-center my-5">
              <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/McDonald%27s_Golden_Arches.svg/1200px-McDonald%27s_Golden_Arches.svg.png" class="img-thumbnail" alt="Mac Donalds" width="100" height="100">
              <h4 class="display-5">Empresa X- Investimento em WebDesign</h4>
              <br>
              <p>Descrição do Investimento</p>
              <br>
              <br>
              <img src="https://upload.wikimedia.org/wikipedia/pt/thumb/c/cf/Logotipo_do_Burger_King.svg/1024px-Logotipo_do_Burger_King.svg.png" class="img-thumbnail" alt="Burguer King" width="100" height="100">
              <h4 class="display-5">Empresa Y- Investimento em Inteligencia Artificial</h4>
              <br>
              <p>Descrição do Investimento</p>
              <br>
              <br>
              <img src="https://www.subway.com/~/media/Base_English/Images/Branding/subway-logo-new-1200x630.png" class="img-thumbnail" alt="Subway" height="100" width="100">
              <h4 class="display-5">Empresa Z- Investimento em BIGDATA</h4>
              <br>
              <p>Descrição do Investimento</p>
              <br>
              <br>
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTQqZfJG11IvDis6RzdvHrV62aCkcXhZY2YO4cAUekW-KgBaIyg" class="img-thumbnail" alt="Bobs" height="100" width="100">
              <h4 class="display-5">Empresa A- Investimento em Desenvolvimento Tecnologico</h4>
              <br>
              <p>Descrição do Investimento</p>
              <br>
              <br>
            </div>
    </div>