<div class="row bg-secondary text-white">
        <div class="col-12 text-center my-5 ">
        <h1 class="display-3">Empresas</h1>
        </div>
        </div> 
        <div class="col-12 text-center my-5">
              <img src="" class="img-thumbnail" alt="Godoy Tec" width="100" height="100">
              <h4 class="display-5">Godoy Tec- Investimento em Design Gráfico</h4>
              <br>
              <p>Com o objetivo de crescer no mercado tecnologico, nós da Godoy Tec temos o foco em Web Design que seria criação de web sites profissionais
              para qualquer tipo de empresa ou pessoa física, temos a proposta de melhorar nossas ferramentas de trabalho e o número de participantes em nossa empresa,
              com isso contamos com sua ajuda para crescermos no mercado e propor um web site digno com qualidade.</p>
              <br>
              <br>
              <hr>
              <img src="" class="img-thumbnail" alt="Tec Guerra" width="100" height="100">
              <h4 class="display-5">Tec Guerra- Investimento em Inteligencia Artificial</h4>
              <br>
              <br>
              <p>Nós da Tec Guerra temos o objetivo de adentrar no mercado tecnológico de inteligencia artificial, com isso contamos com a colaboração de todos para
              realizar esta conquista, através de criações de aplicação que aprenda com as bases de dados e podem ser treinadas para tratar situações de negócio real,
              possuimos uma grande leva de algoritmos que são utilizados para a inteligencia artificial.</p>
              <br>
              <br>
              <hr>
              <img src="\imagens\cinnamon.png\" class="img-thumbnail" alt="Cinnamon" height="100" width="100">
              <h4 class="display-5">Cinnamon- Investimento em Big Data</h4>
              <br>
              <br>
              <p>Com o objetivo de ganhar destaque dentre as empresas com foco em Big Data, possuimos funcionarios com grande capacidade de desenvolvimento
              e somos a favor de trabalho justo para todos, nosso foco é aumentar nosso número de colaboradores na empresa e aumentar o nível de nossas ferramentas de trabalho
              a Big Data é a área do conhecimento que estuda como tratar, analisar e obter informações a partir de conjuntos de dados grandes demais para serem analisados por sistemas tradicionais.</p>
              <br>
              <br>
              <hr>
              <img src="\imagens\crp.png\" class="img-thumbnail" alt="CRP Tec" height="100" width="100">
              <h4 class="display-5">CRP Tec- Investimento em Desenvolvimento de Software</h4>
              <br>
              <p>Nós da CRP Tec temos como foco desenvolvimento de software (programas) em geral, com objetivo de atender qualquer demanda do mercado,
              para pequenas e grandes empresas ou pessoa física, queremos também poder ganhar visibilidade no mercado de desenvolvimento e ser reconhecido pelo mesmo, através
              de novas ferramentas de trabalho e aumentar o numero de colaboradores na empresa.</p>
              <br>
              <br>
            </div>
    </div>