<div class="row bg-secondary text-white">
        <div class="col-12 text-center my-5 ">
        <h1 class="display-3">Investidores</h1>
        </div>
        </div> 
        <div class="col-12 text-center my-5">
            <h3 class="display-4">Importância de Investidores</h3>
        </div>    
        <div class="col-12 text-center my-5">
          <p>O perfil do investidor é fundamental para seleção da carteira de investimentos que lhe deixará mais próximo ao seu objetivo.
              É preciso considerar algumas características pessoais do investidor, sua situação financeira e objetivos para identificar quais produtos atenderão suas necessidades.
              As perguntas devem identificar o perfil de risco, valor do investimento, prazo de aplicação e qualificação do investidor.</p>
        </div>
        <hr>
        <div class="col-12 text-center my-5">
          <h3 class="display-4">Por que investir?</h3>
      </div>    
      <div class="col-12 text-center my-5">
        <p>Antes de pensar em investir, você deve se fazer a seguinte pergunta: “Para que vou aplicar meu dinheiro?”
            Se você ainda não tiver a resposta, pare e reflita. Ter um objetivo é o primeiro passo para um investimento de sucesso. 
            Analise, antes de tudo, a sua situação financeira. Anote em um papel, o que você possui de bens (e aí você pode incluir carro, casa etc), quanto dispõe de capital (ou seja, quanto você tem no banco)
           e quais são as suas despesas e dívidas( prestações, cartões de crédito, despesas mensais, absolutamente tudo).
            Nada deverá escapar deste “pente fino”, pois do contrário, você pode se prejudicar ao gastar um dinheiro que pode lhe fazer falta.</p>
      </div>  
      <hr>
      <div class="col-12 text-center my-5">
        <h3 class="display-4">Invista agora com a gente!</h3>
    </div>
</div>     