<div class="row bg-secondary text-white">
        <div class="col-12 text-center my-5 ">
        <h1 class="display-3">Investidores</h1>
        </div>
        </div> 
        <div class="col-12 text-center my-5">
            <h3 class="display-4">Importância de Investidores</h3>
        </div>    
        <div class="col-12 text-center my-5">
          <p>Texto de importância dos investidores</p>
        </div>
        <hr>
        <div class="col-12 text-center my-5">
          <h3 class="display-4">Por que investir?</h3>
      </div>    
      <div class="col-12 text-center my-5">
        <p>Texto explicando o por que deve-se investir</p>
      </div>  
      <hr>
      <div class="col-12 text-center my-5">
        <h3 class="display-4">Invista agora com a gente!</h3>
    </div>    
    <div class="col-12 text-center my-5">
      <a class="btn btn-dark" href="/" role="button" >Invista Já</a>
    </div>
</div>     