<div class="row bg-secondary text-white">
        <div class="col-12 text-center my-5">
          <h1 class="display-3">Sobre Nós</h1>
        </div>
        </div>
        <div class="col-12 text-center my-5">
            <h3 class="display-4">Para qualquer dúvida ou feedback estaremos a disposição.</h3>
            <br>
            <h4 class="display-5">Segue lista de contato, email e endereço para contato.</h4>
          </div>
        <div class="col-md-6 offset-md-3">
            <div class="col-12 text-center my-5">
              <h5 class="display-7">Contato:<br><br>Pedro- (xx)xxxxx-xxxx<br><br>
                Email:<br><br>Pedro- phgodoy@gmail.com<br><br>
                Endereço:<br><br>Av. Romano do Norte, 00101 - Jardin do Norte, Ribeirão Preto - SP, 14104-000</h5>
            </div>
        </div> 
    </div>