<div class="row bg-secondary text-white">
        <div class="col-12 text-center my-5">
          <h1 class="display-3">Sobre Nós</h1>
        </div>
        </div>
        <div class="col-12 text-center my-5">
            <h3 class="display-4">Para qualquer dúvida ou feedback estaremos a disposição.</h3>
            <br>
            <h4 class="display-5">Segue lista de contato, email e endereço para contato.</h4>
          </div>
        <div class="col-md-6 offset-md-3">
            <div class="col-12 text-center my-5">
              <h5 class="display-7">Contato:<br><br>Gabriel- (16)98822-2753<br>Pedro- (16)98250-2853<br><br>
                Email:<br><br>Gabriel- gabriel.gueraco@gmail.com<br>Pedro- phgodoy12@gmail.com<br><br>
                Endereço:<br><br>Av. Costábile Romano, 2201 - Ribeirânia, Ribeirão Preto - SP, 14096-900</h5>
            </div>
        </div> 
    </div>