<?php 

?>
<div class="row">
    <table id="dynamic-table" class="display table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th class="col-md-1 center">EMPRESA</th>
                <th class="col-md-1 center">VLR_INVESTIDO</th>
                <th class="col-md-1 center">PARCELA</th>
                <th class="col-md-1 center">VLR_PARCELA</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($this->view->empresas as $empresa){ ?>
            <tr>
                <td class="center"><?php  print_r($empresa['EMPRESA']); ?></td>
                <td class="center"><?php  print_r($empresa['VLR_INVESTIDO']); ?></td>
                <td class="center"><?php  print_r($empresa['PARCELA']); ?></td>
                <td class="center"><?php  print_r($empresa['VLR_PARCELA']); ?></td>
              
             
            </tr>
        <?php } ?>    
        </tbody>
    </table>

</div>   
