<div class="row bg-secondary text-white">
      <div class="col-12 text-center my-5">
        <h1 class="display-3">Bem Vindo <?php print_r($_SESSION['NOME']); ?></h1>
      </div>
    </div>
    <br>
    <div class="container" >
    <div id="carouselSite" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselSite" data-slide-to="0" class="active"></li>
        <li data-target="#carouselSite" data-slide-to="1"></li>
        <li data-target="#carouselSite" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="/imagens/investimento_2.jpg" class="img-fluid d-block w-100">
          <div class="carousel-caption d-none d-md-block text-light display-4">
            <h1>Investimentos</h1>
            <p>Start para seu Investimento ou Empresa</p>
          </div>
        </div>
        <div class="carousel-item">
          <img src="/imagens/agenda.jpg" class="img-fluid d-block w-100">
        </div>
        <div class="carousel-item">
            <img src="/imagens/agenda2.jpg" class="img-fluid d-block w-100">
          </div>
      </div>
      <a class="carousel-control-prev" href="#carouselSite" role="button" data-slide="prev">
        <spam class="carousel-control-prev-icon"></spam>
        <spam class="sr-only">Anterior</spam>
      </a>
      <a class="carousel-control-next" href="#carouselSite" role="button" data-slide="next">
        <spam class="carousel-control-next-icon"></spam>
        <spam class="sr-only">Avançar</spam>
      </a>
    </div class="container">
  </div>
        <div class="col-12 text-left my-5">
            <h3 class="display-5">Objetivo:</h3>
            <br>
            <p class="display-6">A P&G Investimentos tem como objetivo auxiliar empresas com foco em tecnologia de pequeno e médio porte, facilitando o acesso a um investidor, dando visibilidade
              para a empresa associada e destaca-la no mercado, focando em empresas com capacidade de desenvolvimento tecnológico e rentável para a economia. Para investidores temos o objetivo de
              através de nossa plataforma mostrar empresas que estão em crescente no mercado tecnológico e grande potêncial econômico, nosso site conta com um ranking das empresas que possuiram maior
              taxa de aceitação pelos investidores, além do ranking nossa página "Empresas" possui um portifolio com todas empresas que trabalhamos e seus respectivos projetos.
            </p>
            <h3 class="display-5">Investimentos:</h3>
            <br>
            <p class="display-6">Nossos investimentos são feitos pelo próprio site, onde você pode selecionar a empresa que deseja investir, após clicar na empresa desejada e ler sobre,
              há um botão escrito "Invista Agora", após clicar no botão você será redirecionado para a página de investimento onde finalizará o investimento, selecionando valor e número
              de parcelas que deseja dividir o valor investido.
            </p>
            <h3 class="display-5">Agenda 2030:</h3>
            <br>
            <p class="display-6">Nós da P&G temos o orgulho de estar participando da Agenda 2030 para um desenvolvimento mais sustentável para o mundo,
            através de 17 objetivos de desenvolvimento sustentável, e para começarmos escolhemos o objetivo numero 9 que segue a área de Industria, Inovação e Infraestrutura.
            </p>
            <div class="col-12 text-center my-5">
                <h2 class="display-6">Conheça agora nossos investimentos</h2>
            </div>
            <div class="col-12 text-center my-5">
            <a class="btn btn-dark" href="/investir" role="button">Investimentos</a>
            </div>
          </div>
    </div>
    </div>