<html lang="pt-br">
    <header>
      <!-- Favicon -->
      <link rel="shortcut icon" href="/favicon.ico" type="image/x-png" >
      <!-- Meta tags Obrigatórias -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Fontawesome -->
        <link rel="stylesheet"  type="text/css"  href="/assets/fontawesome/css/all.css" >
        
        
        <title>P&G Investimentos</title>
        <!-- Bootstrap css -->
        <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css" >
        <!-- Style css -->
        <link rel="stylesheet" type="text/css" href="assets/css style/style.css" >
    </header>
    <body class = "text-center">
      <div class="container text-center">
        <h1>Pagamento realizado com sucesso </h1>
        <br>
        <a href="/indexInvestidor" class="btn btn-dark btn-primary btn-lg active" role="button" aria-pressed="true">Voltar ao Menu</a>
      </div>
      </button>
    </body> 
</html>     